### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by HaojiaWu** [kanaverse/kana#216]
Hi team,
thanks for developing kana. When I upload my h5 file from 10x, and click "analyze", I came across the type error:
```
TypeError: Failed to fetch
```
Do you have any idea how to fix it? 
Any input will be greatly appreciated!
<img width="662" alt="Screenshot 2023-05-16 at 11 09 29 AM" src="https://github.com/kanaverse/kana/assets/29445616/b28d6094-db3b-449e-ae50-d5fef66a03fa">

**Comment by LTLA** [comment]
Hm. Looks like it's failing when it tries to fetch the mitochondrial gene lists from [here](https://github.com/kanaverse/kana-special-features). I do see an error on our proxy service's logs but the reason is not apparent, maybe a network error inside the proxy.

Does this still happen if you refresh the page and try again? If so, do the following to help us debug the issue (on Chrome):

1. Right click anywhere on the page.
2. Click on "inspect" to open the Chrome developer tools.
3. Click on the network tab.
4. Refresh the page and re-attempt the analysis. The failed request should show up as a red entry in the network requests. 
5. Give us a screenshot of the table of requests.

**Comment by HaojiaWu** [comment]
Hi Aaron,
Thanks for the quick response. Here are the errors under the network tab. 

<img width="552" alt="Screenshot 2023-05-16 at 11 41 20 AM" src="https://github.com/kanaverse/kana/assets/29445616/695f615b-40ce-4aa5-84ae-099d6c37a180">

**Comment by LTLA** [comment]
Several points:

- You're not quite on the right tab, you need to go to Network (click on the `>>` next to `Elements` and `Console`). But it doesn't matter here, as the console logs already describe the problem.
- In the proxy logs, I only see a client disconnect. So, nothing wrong with the proxy itself.
- The network error is concerning. Are you behind a VPN or firewall that might be intercepting requests? You can try clicking on the `https://cors-proxy...` link and see if you can access the resource directly.

**Comment by HaojiaWu** [comment]
Ah, thanks for pointing out this. Yes, I am behind a VPN through my university. After I changed the network, everything worked great!
